// Mocks generated by Mockito 5.4.5 from annotations
// in photo_gallery_app/test/domain/use_cases/photo_gallery/photo_gallery_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:photo_gallery_app/api/client/api_result.dart' as _i4;
import 'package:photo_gallery_app/domain/entities/photo_entity.dart' as _i5;
import 'package:photo_gallery_app/domain/repositories/photo_gallery/photo_gallery_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PhotoGalleryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhotoGalleryRepository extends _i1.Mock
    implements _i2.PhotoGalleryRepository {
  MockPhotoGalleryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.PhotoEntity>?>> fetchPhotoGallery({
    required int? page,
    required int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPhotoGallery,
          [],
          {
            #page: page,
            #perPage: perPage,
          },
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.PhotoEntity>?>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.PhotoEntity>?>>(
          this,
          Invocation.method(
            #fetchPhotoGallery,
            [],
            {
              #page: page,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.PhotoEntity>?>>);
}
